# 1. ConfigMap: สำหรับเก็บค่าคอนฟิกทั่วไปที่ไม่เป็นความลับ
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  db_name: "albaly_insights"
---
# 2. Secret: สำหรับเก็บรหัสผ่าน (Base64 Encoded)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # albaly_user
  username: YWxiYWx5X3VzZXI=
  # albaly_password
  password: YWxiYWx5X3Bhc3N3b3Jk
---
# 3. PVC: สำหรับจองพื้นที่เก็บข้อมูลใน Drive D: (ผ่าน Docker Desktop)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# 4. Deployment: ตัวควบคุมการรันคอนเทนเนอร์ Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        # ดึง Username จาก Secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        # ดึง Password จาก Secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db_name
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
# 5. Service: ช่องทางเชื่อมต่อจากแอป Next.js และเครื่อง Local
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer 
  selector:
    app: postgres
  ports:
  - name: db-port
    port: 5435       # พอร์ตที่ Service รับข้อมูล
    targetPort: 5432 # พอร์ตจริงที่ Container ใช้งาน